config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'top#index'
  resources :tops
  resources :users, only: :show
  resources :books do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  #読書状況（ActiveHash）のアソシエーションの設定
  belongs_to_active_hash :reading_situation
  #評価（ActiveHash）のアソシエーションの設定
  belongs_to_active_hash :evaluation

  #アソシエーション
  belongs_to :user
  has_one_attached :image
  has_one_attached :cover


  #検索機能
  def self.search(search)
    if search != ""
      Book.where('title LIKE(?)', "%#{search}%")
      Book.where('author LIKE(?)', "%#{search}%")
      Book.where('genre LIKE(?)', "%#{search}%")
    else
      Book.all
    end
  end

  #本情報
  #必須であること
  with_options presence: true do
    #タイトル
    validates :title
    #表紙
    validates :cover
    #感想・要約（画像）
    validates :image
    #感想・要約
    validates :impression
    #登録日
    validates :record_date
    #読書状況
    validates :reading_situation_id
  end

  #「--」の時は保存できないようにする
  with_options numericality: { other_than: 1 } do
    #カテゴリーの選択
    validates :reading_situation_id
  end

end

app/models/evaluation.rb
class Evaluation < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '☆☆☆☆☆' },
    { id: 3, name: '★☆☆☆☆' },
    { id: 4, name: '★★☆☆☆' },
    { id: 5, name: '★★★☆☆' },
    { id: 6, name: '★★★★☆' },
    { id: 7, name: '★★★★★' }
  ]
 end

app/models/reading_situation.rb
class ReadingSituation < ActiveHash::Base
  self.data = [
   { id: 1, name: '--' },
   { id: 2, name: '読んだ本' },
   { id: 3, name: '読みたい本' }
 ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :books

  #ユーザー情報
  #ネームが必須であること
  validates :name, presence: true
  #メールアドレスが必須であること
  validates :email, presence: true
  #メールアドレスが一意性であること
  validates :email, uniqueness: true
  #メールアドレスは@を含む必要があること
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }
  #パスワードが必須であること
  validates :password, presence: true
  #パスワードは6文字以上であること
  validates :password, length: { minimum: 6 }
  #パスワードは半角英数字混合であること
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
  validates :password, format: { with: VALID_PASSWORD_REGEX }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :edit, :search]


  def index
    @books = Book.order("created_at DESC")
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      return redirect_to "/users/#{current_user.id}"
    end
      render 'new'
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to "/users/#{current_user.id}"
  end

  def search
    @books = Book.search(params[:keyword])
  end

  private

  def book_params
    params.require(:book).permit(:reading_situation_id, :record_date, :title, :cover, :genre, :author, :publishing, :memo, :impression, :image, :evaluation_id).merge(user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to user_session_path
    end
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @books = current_user.books
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_bookshelf.html.erb
<div class="search-titel">
  〜　本棚一覧　〜
</div>

<div class="bookshelf">
  <% @books.each do |book| %>
  <div class="book-flame">
    <div class="book-cover-flame">
      <%= image_tag book.cover, class:"book-index-img" %>
    </div>
    <div class="book-informations">
      <div class="book-title">
        <%= book.title %>
      </div>
      <div class="book-author">
        著者：  <%= book.author %>
      </div>
      <div class="book-genre">
        ジャンル：  <%= book.genre %>
      </div>
      <div class="book-record-date">
       登録日：  <%= book.record_date %>
      </div>
    </div>
    <div class="book-logo" id="lists4">
      <%= link_to image_tag('book-icon.png' , size: '60x60'), book_path(book.id) %>
    　<div class="show-lists4 hidden" id="pull-down4">
        <div class="hb4-1 hb4-2"></div>
        <div>詳細表示</div>
      </div>
    </div>
  </div>
  <% end %>

  <%# 本の登録がなかった場合、文字が表示される%>
  <% if @books.length == 0 %>
  <div class="book-flame2">
    <div class="empty-titel">
      本を登録しよう！
    </div>
    <%= link_to image_tag('header-logo1.png', size: '35x35'), new_book_path %>
    <div class="empty-titel">
      から登録できるよ！
    </div>
  </div>
  <% end %>
</div

app/views/books/_header.html.erb
<div class="header">
  <div class="header-flame">
    <div class="header-title">
      <%= link_to image_tag('logo.png' , size: '90x90'), root_path %>
    </div>
    
    <%#<div class="bookshelf-header-form">%>
        <%#= form_with(url: search_books_path, local: true, method: :get, class: "search-form") do |form| %>
          <%#= form.text_field :keyword, placeholder: "キーワード入力(タイトル・著者...)", class: "search-input" %>
          <%#= form.submit "検索", class: "search-btn" %>
        <%# end %>
    <%#</div>%>

    <div class="header-logos">
      <div class="header-logo1" id="lists">
        <%= link_to image_tag('header-logo1.png', size: '35x35'), new_book_path %>
        <div class="show-lists hidden" id="pull-down">
          <div class="hb1-1 hb1-2"></div>
          <div id="pull-down-list">本新規登録</div>
        </div>
      </div>
      <div class="header-logo2" id="lists2">
        <%= link_to image_tag('header-logo2.png' , size: '35x35'), "/users/#{current_user.id}" %>
        <div class="show-lists2 hidden" id="pull-down2">
          <div class="hb2-1 hb2-2"></div>
          <div>本棚一覧</div>
        </div>
      </div>
      <div class="header-logo3" id="lists3">
        <%= link_to image_tag('header-logo3.png' , size: '35x35'), destroy_user_session_path, method: :delete %>
        <div class="show-lists3 hidden" id="pull-down3">
          <div class="hb3-1 hb3-2"></div>
          <div><%= current_user.name %></div>
          <div>ログアウト</div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/_search_bookshelf.html.erb
<div class="bookshelf">
  <div class="book-flame">
    <div class="book-cover-flame">
      <%= image_tag book.cover, class:"book-index-img" %>
    </div>
    <div class="book-informations">
      <div class="book-title">
        <%= book.title %>
      </div>
      <div class="book-author">
        著者：  <%= book.author %>
      </div>
      <div class="book-genre">
        ジャンル：  <%= book.genre %>
      </div>
      <div class="book-record-date">
       登録日：  <%= book.record_date %>
      </div>
    </div>
    <div class="book-logo" id="lists4">
      <%= link_to image_tag('book-icon.png' , size: '60x60'), book_path(book.id) %>
    　<div class="show-lists4 hidden" id="pull-down4">
        <div class="hb4-1 hb4-2"></div>
        <div>詳細表示</div>
      </div>
  </div>
</div>

app/views/books/edit.html.erb
<%= render "header" %>


<div class="books-registration-contents">
  <div class="books-registration-main">
    <h2 class="books-registration-title">本の情報を編集</h2>
    <%= form_with model: @book, local: true do |f| %>
      <%# 本の分類分け %>
      <div class="new-books2">
        <div class="weight-bold-text2">
          登録日
          <span class="indispensable">必須</span>
        </div>
      </div>
      <%= f.text_field :record_date, class:"books-text", id:"book-record_date", placeholder:"登録日を記入", maxlength:"10" %>
      <div class="books-detail">
        <div class="weight-bold-text">
          本棚の選択
          <span class="indispensable">必須</span>
        </div>
          <div class="form">
          <%= f.collection_select(:reading_situation_id, ReadingSituation.all, :id, :name, {}, {class:"select-box", id:"book-reading-situation"}) %>
          </div>
      </div>
      <div class="books-detail">
        <div class="weight-bold-text">
          評価の選択
          <span class="indispensable2">任意</span>
        </div>
          <div class="form">
          <%= f.collection_select(:evaluation_id, Evaluation.all, :id, :name, {}, {class:"select-box", id:"book-evaluation"}) %>
          </div>
      </div>
      <%# /本の分類分け %>

      <%# 表紙画像 %>
      <div class="img-upload">
        <div class="weight-bold-text">
          表紙
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :cover, id:"book-cover" %>
        </div>
      </div>
      <%# /表紙画像 %>

      <%#　本の情報　%>
      <%# タイトル、ジャンル、著者、出版 %>
      <div class="new-books">
        <div class="weight-bold-text">
          タイトル
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :title, class:"books-text", id:"book-title", placeholder:"本のタイトル（必須 100文字まで)", maxlength:"100" %>
        <div class="books-explain">
          <div class="weight-bold-text">
            ジャンル
            <span class="indispensable2">任意</span>
          </div>
          <%= f.text_field :genre, class:"books-text", id:"book-genre", placeholder:"本のジャンル（任意 20文字まで）（小説、漫画、ビジネス書など）",maxlength:"20" %>
        </div>
        <div class="books-explain">
          <div class="weight-bold-text">
            著者
            <span class="indispensable2">任意</span>
          </div>
          <%= f.text_field :author, class:"books-text", id:"book-author", placeholder:"本の著者（任意 50文字まで）",maxlength:"50" %>
        </div>
        <div class="books-explain">
          <div class="weight-bold-text">
            出版
            <span class="indispensable2">任意</span>
          </div>
          <%= f.text_field :publishing, class:"books-text", id:"book-publishing", placeholder:"本の出版（任意 50文字まで）",maxlength:"50" %>
        </div>
      </div>
      <%# /商品名と商品説明 %>

      <%# メモ・感想・要約 %>
      <div class="books-explain">
          <div class="weight-bold-text">
            メモ
            <span class="indispensable2">任意</span>
          </div>
          <%= f.text_area :memo, class:"books-text", id:"book-memo", placeholder:"メモ（任意 200文字まで）" ,rows:"4" ,maxlength:"200" %>
      </div>
      <div class="books-explain">
          <div class="weight-bold-text">
            感想・要約
            <span class="indispensable2">任意</span>
          </div>
          <%= f.text_area :impression, class:"books-text", id:"book-impression", placeholder:"感想・要約（任意 3000文字まで）" ,rows:"7" ,maxlength:"3000" %>
      </div>
      <%# /メモ・感想・要約 %>

      <%# まとめ画像 %>
      <div class="img-upload">
        <div class="weight-bold-text">
          感想・要約（画像）
          <span class="indispensable2">任意</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
         </p>
         <%= f.file_field :image, id:"book-image" %>
        </div>
      </div>
     <%# /まとめ画像 %>
     <%# 下部ボタン %>
      <div class="registration-btn-contents1">
        <%= f.submit "変更する" ,class:"registration-btn" %>
      </div>
      <div class="registration-btn-contents2">
        <%=link_to 'もどる', "/users/#{current_user.id}" , class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
  </div>
  <% end %>
</div>

app/views/books/index.html.erb
<%= render "header" %>

<%= render "bookshelf" %>

app/views/books/new.html.erb
<%= render "header" %>


<div class="books-registration-contents">
  <div class="books-registration-main">
    <h2 class="books-registration-title">本の情報を入力</h2>
    <%= form_with model: @book, local: true do |f| %>
      <%# 本の分類分け %>
      <div class="new-books2">
        <div class="weight-bold-text2">
          登録日
          <span class="indispensable">必須</span>
        </div>
      </div>
      <%= f.text_field :record_date, class:"books-text", id:"book-record_date", placeholder:"登録日を記入", maxlength:"10" %>
      <div class="books-detail">
        <div class="weight-bold-text">
          本棚の選択
          <span class="indispensable">必須</span>
        </div>
          <div class="form">
          <%= f.collection_select(:reading_situation_id, ReadingSituation.all, :id, :name, {}, {class:"select-box", id:"book-reading-situation"}) %>
          </div>
      </div>
      <div class="books-detail">
        <div class="weight-bold-text">
          評価の選択
          <span class="indispensable2">任意</span>
        </div>
          <div class="form">
          <%= f.collection_select(:evaluation_id, Evaluation.all, :id, :name, {}, {class:"select-box", id:"book-evaluation"}) %>
          </div>
      </div>
      <%# /本の分類分け %>

      <%# 表紙画像 %>
      <div class="img-upload">
        <div class="weight-bold-text">
          表紙
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :cover, id:"book-cover" %>
        </div>
      </div>
      <%# /表紙画像 %>
      <%#　本の情報　%>
      <%# タイトル、ジャンル、著者、出版 %>
      <div class="new-books">
        <div class="weight-bold-text">
          タイトル
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :title, class:"books-text", id:"book-title", placeholder:"本のタイトル", maxlength:"100" %>
        <div class="books-explain">
          <div class="weight-bold-text">
            ジャンル
            <span class="indispensable2">任意</span>
          </div>
          <%= f.text_field :genre, class:"books-text", id:"book-genre", placeholder:"本のジャンル（小説、漫画、ビジネス書など）",maxlength:"20" %>
        </div>
        <div class="books-explain">
          <div class="weight-bold-text">
            著者
            <span class="indispensable2">任意</span>
          </div>
          <%= f.text_field :author, class:"books-text", id:"book-author", placeholder:"本の著者",maxlength:"50" %>
        </div>
        <div class="books-explain">
          <div class="weight-bold-text">
            出版
            <span class="indispensable2">任意</span>
          </div>
          <%= f.text_field :publishing, class:"books-text", id:"book-publishing", placeholder:"本の出版",maxlength:"50" %>
        </div>
      </div>
      <%# /商品名と商品説明 %>

      <%# メモ・感想・要約 %>
      <div class="books-explain">
          <div class="weight-bold-text">
            メモ
            <span class="indispensable2">任意</span>
          </div>
          <%= f.text_area :memo, class:"books-text", id:"book-memo", placeholder:"メモ" ,rows:"4" ,maxlength:"200" %>
      </div>
      <div class="books-explain">
          <div class="weight-bold-text">
            感想・要約
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :impression, class:"books-text", id:"book-impression", placeholder:"感想・要約" ,rows:"7" ,maxlength:"3000" %>
      </div>
      <%# /メモ・感想・要約 %>

      <%# まとめ画像 %>
      <div class="img-upload">
        <div class="weight-bold-text">
          感想・要約（画像）
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
         </p>
         <%= f.file_field :image, id:"book-image" %>
        </div>
      </div>
     <%# /まとめ画像 %>
     <%# 下部ボタン %>
      <div class="registration-btn-contents1">
        <%= f.submit "登録する" ,class:"registration-btn" %>
      </div>
      <div class="registration-btn-contents2">
        <%=link_to 'もどる', "/users/#{current_user.id}" , class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
  </div>
  <% end %>
</div>

app/views/books/search.html.erb
<%= render "header" %>

<div class="search-titel">
  〜　検索結果　〜
</div>

<div class="search-bookshelf">
  <% @books.each do |book| %>
  <%= render partial: "books/search_bookshelf", locals: { book: book } %>
  <% end %>
</div>

app/views/books/show.html.erb
<%= render "header" %>

<%#タイトル　表示%>
<div class="book-show-flame">
  <div class="book-show">
    <div class="book-show-border">
      <div class="book-show-title">
        <%= @book.title %>
      </div>
    </div>

<%#カバー・著者・ジャンル・登録日　表示%>
    <div class="book-show-box1">
      <div class="book-show-cover1">
        <%= image_tag @book.cover, class:"book-show-cover2" %>
      </div>
      <div class="book-show-informations1">
        <div class="book-text">
          〜著者〜
        </div>
        <div class="book-show-author">
          <%= @book.author %>
        </div>
        <div class="book-text">
          〜出版〜
        </div>
        <div class="book-show-publishing">
          <%= @book.publishing %>
        </div>
        <div class="book-text">
          〜ジャンル〜
        </div>
        <div class="book-show-genre">
          <%= @book.genre %>
        </div>
        <div class="book-text">
          〜登録日〜
        </div>
        <div class="book-show-record-date">
          <%= @book.record_date %>
        </div>
      </div>
    </div>
<%#評価、本棚　表示%>

    <div class="book-show-informations2">
      <div class="book-reading-situation1">
        <div class="book-reading-situation2">
          〜本棚の種類〜
        </div>
        <div class="book-show-reading-situation">
          <%= @book.reading_situation.name %>
        </div>
      </div>
      <div class="brank">
      </div>
      <div class="book-evaluation1">
        <div class="book-evaluation2">
          〜評価〜
        </div>
        <div class="book-show-evaluation">
          <%= @book.evaluation.name %>
        </div>
      </div>
    </div>

<%#メモ・感想要約・感想要約（画像）表示%>
    <div class="book-show-informations3">
      <div class="book-memo-text">
        〜メモ〜
      </div>
      <div class="book-memo">
        <%= @book.memo %>
      </div>
      <div class="book-impression-text">
          〜感想・要約〜
      </div>
      <div class="book-impression">
        <%= @book.impression %>
      </div>
      <div class="book-impression-text">
          〜感想・要約(画像)〜
      </div>
    </div>
      <div class="book-show-image1">
          <%= image_tag @book.image, class:"book-show-image2" %>
      </div>

<%# 編集・削除ボタン 表示%>
    <div class="book-show-btns">
      <div class="show-btn-contents">
        <%=link_to '編集', edit_book_path, method: :get, class:"show-edit-btn" %>
      </div>
      <div class="show-btn-contents">
        <%=link_to '削除', book_path(@book.id), method: :delete, class:"show-delete-btn" %>
      </div>
      <div class="show-btn-contents">
        <%=link_to '戻る', "/users/#{current_user.id}" , class:"show-back-btn" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyLibrary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="index.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/index.html.erb
<div class="top-header">
  <div class="users-header-logo">
    <%= link_to image_tag('logo.png' , size: '300x300'), "/" %>
  </div>
</div>

<div class="main-view" >
  <div class="users-header-logo">
  </div>
    <% if user_signed_in? %>
    <span class="top-moji">my library</span>
    <span class="top-moji">あなただけの、図書館を</span>
    <span class="top-moji">〜<%= current_user.name %>〜</span>
    <% else %>
    <span class="top-moji">my library</span>
    <span class="top-moji">あなただけの、図書館を</span>
    <% end %>
    <div class="top-icon-logo">
      <% if user_signed_in? %>
        <div class="icon-box">
          <%= link_to image_tag('login.jpg' , size: '200x50'),  "/users/show #{current_user.id}" %>
          <%= link_to image_tag('logout.jpg' , size: '200x50'), destroy_user_session_path, method: :delete %>
        </div>
      <% else %>
         <div class="icon-box">
          <%= link_to image_tag('signinlogo.jpg' , size: '200x50'), new_user_registration_path %>
          <%= link_to image_tag('signuplogo.jpg' , size: '200x50'), new_user_session_path %>
        </div>
      <% end %>
    </div>
</div>

<div class="top-footer">
  <div class="left-footer">
    <ul>
      <li>種別：本管理ツール</li>
      <li>制作：rui murakai</li>
    </ul>
  </div> 
  <div class="right-footer">
  2020 orignal application
  </div>
</div>

app/views/users/show.html.erb
<%= render "books/header" %>

<div class="search-titel">
  <span>〜　<%= current_user.name %> 　の本棚一覧　〜</span>
</div>

<div class="bookshelf">
  <% @books.each do |book| %>
  <div class="book-flame">
    <div class="book-cover-flame">
      <%= image_tag book.cover, class:"book-index-img" %>
    </div>
    <div class="book-informations">
      <div class="book-title">
        <%= book.title %>
      </div>
      <div class="book-author">
        著者：  <%= book.author %>
      </div>
      <div class="book-genre">
        ジャンル：  <%= book.genre %>
      </div>
      <div class="book-record-date">
       登録日：  <%= book.record_date %>
      </div>
    </div>
    <div class="book-logo" id="lists4">
      <%= link_to image_tag('book-icon.png' , size: '60x60'), book_path(book.id) %>
    　<div class="show-lists4 hidden" id="pull-down4">
        <div class="hb4-1 hb4-2"></div>
        <div>詳細表示</div>
      </div>
    </div>
  </div>
  <% end %>

  <%# 本の登録がなかった場合、文字が表示される%>
  <% if @books.length == 0 %>
  <div class="book-flame2">
    <div class="empty-titel">
      本を登録しよう！
    </div>
    <%= link_to image_tag('header-logo1.png', size: '35x35'), new_book_path %>
    <div class="empty-titel">
      から登録できるよ！
    </div>
  </div>
  <% end %>
</div>